controller:
  adminUser: admin
  adminPassword: admin123

  serviceType: NodePort

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow

persistence:
  enabled: true
  size: 10Gi