expose:
  type: nodePort
  tls:
    enabled: false

externalURL: http://harbor.local

harborAdminPassword: Harbor12345

persistence:
  persistentVolumeClaim:
    registry:
      storageClass: local-storage
    database:
      storageClass: local-storage
    redis:
      storageClass: local-storage
    jobservice:
      storageClass: local-storage
    trivy:
      storageClass: local-storage